import type { Metadata } from "next";

import Image from "next/image";

import logo from "@/assets/brubank_logo.png";

import "./globals.css";

export const metadata: Metadata = {
  title: "Brubank Transfer",
  description: "Generated by appncy",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen max-w-screen-sm grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <header className="flex items-center justify-center">
          <Image alt="Brubank" className="inline-block" height={150} src={logo} />
        </header>
        <main className="pb-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} Brubank
        </footer>
      </body>
    </html>
  );
}
